## 텐서플로우 1
* Lazy execution
* 텐서 모양과 통로를 미리 정의
* 세션을 생성(tf.Session())하고 실행(session.run())이후에 비로소 텐서(tensor)들이 흘러다님(flow)

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

### 상수

* 상수를 담을 텐서 모양을 정의
* 세션을 실행해야 비로소 값이 흐름

* 상수표현

In [50]:
# 텐서의 모양을 정의
a = tf.constant(1., name='a') # 상수 텐서
b = tf.constant(2., name='b') # 상수 텐서
c = tf.constant([[1., 2.], [3., 4.]]) # 2x2 텐서

In [51]:
# 텐서의 모양만 알려줌
print(a)
print(a+b)
print(c)

Tensor("a_1:0", shape=(), dtype=float32)
Tensor("add_6:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(2, 2), dtype=float32)


In [52]:
# 텐서 연산을 위해서 세션 생성
sess = tf.Session()

* 세션 run으로 세션을 실행해야 그제서야(lazy) 텐서를 통해 값들이 흘러다님

In [53]:
# 1차원 벡터의 값을 a, b로 채움
sess.run([a, b])

[1.0, 2.0]

In [54]:
# 
sess.run(c)

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [55]:
sess.run([a+b])

[3.0]

In [56]:
sess.run(a+b)

3.0

In [57]:
# 원소 마다 1을 더해줌
sess.run(c + 1.)

array([[2., 3.],
       [4., 5.]], dtype=float32)

In [62]:
sess.close()

### 플레이스홀더
* 텐서가 흘러다닐 수 있는 통로
* 세션을 실행한 이후에 이 통로를 통해 값이 흘러다닐 수 있음

In [23]:
# float32 라는 데이터를 흘려보낼 텐서 정의
a = tf.placeholder(tf.float32)

# float32 라는 데이터를 흘려보낼 텐서 정의
b = tf.placeholder(tf.float32)

# float32 텐서를 더하는 연산을 하는 텐서 정의
c = a + b

In [65]:
sess = tf.Session()

In [66]:
# a 플레이스홀더에 1.23 을 대입하여 a의 결과를 확인
sess.run(a, feed_dict={a:1.23})

array(1.23, dtype=float32)

In [67]:
# b 플레이스홀더에 2.34 을 대입하여 b의 결과를 확인
sess.run(b, feed_dict={b:2.34})

array(2.34, dtype=float32)

In [68]:
# a 에 값 넣고, b를 확인하면?
# 값을 흘려보낸 통로와 확인하는 통로가 달라서 에러 발생
sess.run(b, feed_dict={a: 3})

2.0

In [69]:
# a=1., b=1. 을 대입
# 딕셔너리로 값을 넣어줌
sess.run(c, feed_dict={a: 1., b:3.})

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [70]:
# a, b 텐서에 벡터 넣기
sess.run(c, {a: [1., 2.], b:[3., 4.]})

ValueError: Cannot feed value of shape (2,) for Tensor 'a_1:0', which has shape '()'

In [25]:
# a, b 텐서에 매트릭스 넣기
sess.run(c, {a: [[1,2],[3,4]], b:[[3,5,],[7,9]]})

array([[ 4.,  7.],
       [10., 13.]], dtype=float32)

In [75]:
# 상수 정의
d = tf.constant(1, tf.float32)

In [76]:
# 상수가 나옴
sess.run(d)

1.0

In [78]:
# 다른 값 넣을 수도 있음
sess.run(d, {d: 3.14})

array(3.14, dtype=float32)

In [79]:
sess.close()

### 변수

In [80]:
# 값이 변할 수 있는 텐서
# 정규분포에 따라 랜덤한 값으로 초기화하기로 함
W1 = tf.Variable(tf.random_normal([1]))
b1 = tf.Variable(tf.random_normal([1]))
W2 = tf.Variable(tf.random_normal([1, 2]))
b2 = tf.Variable(tf.random_normal([1, 2]))

In [81]:
W1

<tf.Variable 'Variable_4:0' shape=(1,) dtype=float32_ref>

In [82]:
b1

<tf.Variable 'Variable_5:0' shape=(1,) dtype=float32_ref>

In [83]:
W2

<tf.Variable 'Variable_6:0' shape=(1, 2) dtype=float32_ref>

In [84]:
b2

<tf.Variable 'Variable_7:0' shape=(1, 2) dtype=float32_ref>

In [85]:
sess = tf.Session()

In [86]:
# 초기화 하기로 한 값을 정말 초기화
sess.run(tf.global_variables_initializer())

In [87]:
sess.run(W1)

array([1.0646005], dtype=float32)

In [88]:
sess.run(b1)

array([0.6197374], dtype=float32)

In [89]:
sess.run(W2)

array([[-0.20458557, -0.12698849]], dtype=float32)

In [90]:
sess.run(b2)

array([[ 1.5342646 , -0.51589894]], dtype=float32)

In [91]:
for step in range(3):
    W1 = W1 - step
    b1 = b1 - step
    W2 = W2 - step
    b2 = b2 - step
    print('step =', step, ', W1 =', sess.run(W1), ", b1 =", sess.run(b1))
    print('step =', step, ', W2 =', sess.run(W2), ', b2 =', sess.run(b2))

step = 0 , W1 = [1.0646005] , b1 = [0.6197374]
step = 0 , W2 = [[-0.20458557 -0.12698849]] , b2 = [[ 1.5342646  -0.51589894]]
step = 1 , W1 = [0.06460047] , b1 = [-0.3802626]
step = 1 , W2 = [[-1.2045856 -1.1269885]] , b2 = [[ 0.53426456 -1.515899  ]]
step = 2 , W1 = [-1.9353995] , b1 = [-2.3802626]
step = 2 , W2 = [[-3.2045856 -3.1269884]] , b2 = [[-1.4657354 -3.515899 ]]


In [96]:
# 최종 값
sess.run([W1, b1])

[array([-1.9353995], dtype=float32), array([-2.3802626], dtype=float32)]

In [99]:
# 다른 값 넣을 수 있음
sess.run(W1, {W1: [1.44]})

array([1.44], dtype=float32)

In [100]:
sess.close()