# 정규 분포 샘플링

In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
tf.__version__

'1.15.0'

![fig1](https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Normal_Distribution_PDF.svg/340px-Normal_Distribution_PDF.svg.png)

* 정규분포의 히스토그램을 그려보면 좌우대칭 종모양
* 정규분포에서 랜덤 샘플링한다는 의미는 위 그림에서 랜덤하게 X값을 뽑아낸다는 의미
* 위 그림에서 서로 다른 색으로 된 다양한 정규분포
  * 파란선은 평균(mean)이 0, 변량(variance)이 0.2
  * 붉은선은 평균이 0, 변량이 1.0
  * 파란선과 붉은선을 비교해보면, 변량이 작을 수록 평균에 가까운 값을 뽑아낼 확률이 큼

텐서플로우의 ```tf.random_normal()```을 써서 랜덤값을 뽑아보자.

```python
tf.random.normal(
    shape,
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
```
여기에는 위와 같은 인자가 들어감
* shape: 모양, 몇 차원으로 이루어져 있고, 각각의 차원은 몇 개의 원소가 들어가는지
* mean: 정규분포의 평균
* stddev: 정규분포의 표준편차
* dtype: 데이터형
* seed: 값을 정해주면 동일한 값이 뽑힘
* name: 이름

In [24]:
# 하나의 인자만 넣으면 모양만 넣은 것임
a = tf.random_normal([1])

# 즉, a는 아래와 같음
b = tf.random_normal(shape=[1])

In [25]:
a

<tf.Tensor 'random_normal_3:0' shape=(1,) dtype=float32>

In [26]:
b

<tf.Tensor 'random_normal_4:0' shape=(1,) dtype=float32>

In [27]:
# 세션 생성
sess = tf.Session()

In [28]:
sess.run(a)

array([-1.769585], dtype=float32)

In [29]:
sess.run(a)

array([0.6923405], dtype=float32)

In [30]:
sess.run(a)

array([-1.1539906], dtype=float32)

In [31]:
sess.close()

다른 모양도 만들어보자.

In [32]:
a = tf.random_normal(shape=[2, 2])

with tf.Session() as sess:
    print(sess.run(a))

[[-0.59843725 -0.9133385 ]
 [ 0.9251011  -0.44545722]]
